"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQhhXp2ZTGyU_TqrVzCv7YxX-U9T__Pu

# EDA - Prétraitement et Compréhension des Données

**`Importation des librairies`**
"""
import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import geopandas as gpd

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from statsmodels.tsa.arima.model import ARIMA
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score


df_agroclimat = pd.read_excel("agroclimat.xlsx")
geo = gpd.read_file("benin_geographie")


st.title("Contexte du projet")
st.subheader("# - **AgroClimat** # : Une solution intelligente pour la gestion des ressources hydriques, agricoles et la lutte contre le changement climatique")
st.subheader("Agroclimat, c'est Pour la lutte contre les changements climatiques et Pour une agriculture résiliente et productive au Bénin")
st.write("L'agriculture demeure une pierre angulaire de l'économie béninoise, fournissant des moyens de subsistance à une grande partie de la population et contribuant significativement au produit intérieur brut (PIB) du pays. Cependant, la production agricole au Bénin est souvent entravée par des défis climatiques, notamment des variations imprévisibles des précipitations, des températures extrêmes et des événements météorologiques sévères. Ces fluctuations climatiques ont un impact direct sur les rendements agricoles, rendant la production alimentaire plus incertaine et exacerbant les risques pour la sécurité alimentaire.")
st.title("Objectif du projet")
st.write("Le projet AgroClimat a pour objectif de développer un outil de prévision des facteurs climatiques pour mettre en place des mesure relatives pour lutter contre les chnagement climatiques d'une part, et faire des prévisons de la production agricoles en fonction des ces conditions climatiques. L'objectif est de permettre aux acteurs du secteur agricoles et des changement climatiques de mieux anticiper les rendements de leurs cultures en fonction des conditions climatiques préviionneles pour une agriculture résilliente et productive.")
st.title("Objectif spécifiques")
st.write("1. Analyse des données agricoles par produit, par département et par commune.")
st.write("2. Analyse des données climatiques par département, par communes et par type de données (pluviométrie, température, humidité, etc.)")
st.write("3. Analyse des données de rendements agricoles par produit, par département et par commune.")
st.write("4. Analyse des facteurs climatiques et de leur impact sur la production agricole au Bénin pour chaque produit dans chaque communes/département.")
st.write("5. Répartition géographique des facteurs climatiques en république du Bénin par communes/département (Cartographie des facteurs climatiques du Bénin.")
st.write("6. Prévisions des facteurs climatiques et agricoles sur 5 ans pour chaque produit par communes.")
st.write("7. Formulation des recommandations.")
    
st.header("Principaaux résultats attendus")
st.write("1. Répondre aux enjeux de faim et la chairté de la vie au Bénin et en Afrique l’Ouest grâce à un outil d’aide à la décision pour l’amélioration significative de la production et des rendements grâce à une meilleure adaptation aux conditions climatiques")
st.write("2. Optimisation des pratiques culturales : Des recommandations personnalisées pour chaque parcelle et chaque culture, permettant de réduire les risques liés aux aléas climatiques")
st.write("3. Soutien à la décision politique : Les résultats de l'étude pourront servir de base pour l'élaboration de politiques publiques visant à renforcer la sécurité alimentaire et à adapter l'agriculture au changement climatique.")
st.write("4. Anticipation des risques : Des prévisions climatiques précises pour anticiper les risques et prendre les bonnes décisions au bon moment")
st.write("5. Renforcement des capacités : Formation des acteurs locaux à l'utilisation de l'outil et à l'interprétation des données.")
st.write("6. Développement d'un modèle de prédiction des rendements agricoles en fonction des conditions climatiques.")
st.write("7. Renforcer les capacités nationales en matière d'analyse de données climatiques et agricoles.")
st.write("8. Faciliter le partage de connaissances et de bonnes pratiques entre les chercheurs, les agriculteurs et les décideurs.")
st.write("9. Contribuer à la mise en œuvre des Objectifs de développement durable (ODD), notamment l'ODD 2 (éliminer la faim) et l'ODD 13 (mésure relatives pour la lutte contre les changements climatiques).")
st.image("odd.png")

st.header("Méthodologie")
st.write("1. Collecte des données : Collecte des données climatiques, agricoles et géographiques du Bénin.")
st.write("2. Prétraitement des données : Nettoyage, transformation et imputation des données manquantes.")
st.write("3. Exploration des données : Analyse exploratoire des données pour comprendre les relations entre les différentes variables.")
st.write("4. Modélisation : Développement des modèles de prévisions climatiques et des rendements agricoles en fonction des conditions climatiques prévisionnelles.")
st.write("5. Evaluation des modèles : Evaluation des performances des modèles et ajustement des paramètres.")
st.write("6. Interprétation des résultats : Interprétation des résultats pour formuler des recommandations.")
st.write("7. Communication des résultats : Présentation des résultats aux parties prenantes et publication des résultats.")
st.write("8. Formation des acteurs locaux : Formation des acteurs locaux à l'utilisation de l'outil et à l'interprétation des données.")
st.write("9. Développement d'un outil d'aide à la décision : Développement d'un outil d'aide à la décision basé sur les résultats de l'étude.")
st.write("10. Mise en œuvre des recommandations : Mise en œuvre des recommandations pour améliorer la production agricole et renforcer la résilience des agriculteurs face aux changements climatiques.")

st.header("Source de données")
st.write("Les données utilisées dans le cadre de ce projet sont issues de différentes sources, notamment :")
st.write("- Les données climatiques : Les données climatiques sont issues de l'agence météorologique du Bénin. Ces données comprennent des informations sur la pluviométrie, la température, l'humidité, la vitesse du vent, etc.")
st.write("- Les données agricoles : Les données agricoles sont issues du ministère de l'agriculture de l'élévage et de la peche. Ces données comprennent des informations sur les rendements des cultures, les superficies cultivées, et la production agricole.")
st.image("maep.png")
st.write("- Les données géographiques : Les données géographiques sont issues de l'intitut géographiques nationale du Bénin. Ces données comprennent des informations sur les longitutes, les latitudes des communes du Bénin.")    
st.image("ign.jpg")
st.write("Ces données sont collectées, nettoyées, transformées et analysées pour en extraire des informations utiles pour la réalisation de notre objectif.")
