"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQhhXp2ZTGyU_TqrVzCv7YxX-U9T__Pu

# EDA - Prétraitement et Compréhension des Données

**`Importation des librairies`**
"""
import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import geopandas as gpd

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from statsmodels.tsa.arima.model import ARIMA
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score


df_agroclimat = pd.read_excel("agroclimat.xlsx")
geo = gpd.read_file("benin_geographie")


st.title("Exploration des données")
st.write("Dans cette section, nous allons explorer les données agricoles, climatiques et géographiques du Bénin pour comprendre la structure, le contenus et les relations entre les différentes variables.")    
df_agroclimat = df_agroclimat.rename(columns={"Communes": "Departement"})
df_agroclimat = df_agroclimat.rename(columns={"Département": "Communes"})
#Contenus de Communes
#Contenus de Communes
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['ABOMEY0CALAVI', 'ABOMEY CALAVI'], 'ABOMEY-CALAVI')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['DASSA0ZOUME', 'Dassa-Zoumè'], 'DASSA-ZOUME')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['PORTO0NOVO'], 'PORTO-NOVO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['SEME0PODJI'], 'SEME-PODJI')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['ADJA0OUERE', 'Adja-Ouèrè'], 'ADJA-OUERE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['AKPRO0MISSERETE'], 'AKPRO-MISSERETE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['TORI0BOSSITO'], 'TORI-BOSSITO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['TORI'], 'TORI-BOSSITO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['GRAND0POPO'], 'GRAND-POPO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['ZA0KPOTA', 'Za-Kpota'], 'ZA-KPOTA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Ouinhi'], 'OUINHI')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Zagnanado'], 'ZAGNANADO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Zogbodomey'], 'ZOGBODOMEY')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Bantè'], 'BANTE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Glazoué'], 'GLAZOUE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Ouèsse'], 'OUESSE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Savalou'], 'SAVALOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Savè'], 'SAVE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Lokossa', 'LOKOSSA '], 'LOKOSSA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Athiémé'], 'ATHIEME')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Aplahoué'], 'APLAHOUE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Djakotomey'], 'DJAKOTOMEY')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Dogbo'], 'DOGBO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Klouékanmè'], 'KLOUEKANME')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Lalo'], 'LALO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Toviklin'], 'TOVIKLIN')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Kétou'], 'KETOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Pobé'], 'POBE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Kalalé'], 'KALALE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(["N'Dali"], "N'DALI")
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Nikki'], 'NIKKI')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Parakou'], 'PARAKOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Pèrèrè'], 'PERERE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Sinendé'], 'SINENDE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Tchaourou'], 'TCHAOUROU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Banikoara'], 'BANIKOARA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Gogounou'], 'GOGOUNOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Kandi'], 'KANDI')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Karimama'], 'KARIMAMA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Malanville'], 'MALANVILLE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Ségbana'], 'SEGBANA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Abomey'], 'ABOMEY')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Agbangnizoun'], 'AGBANGNIZOUN')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Bohicon'], 'BOHICON')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Covè'], 'COVE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Djidja'], 'DJIDJA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Péhunco', 'PEHOUCO', 'PEHOUNCO'], 'PEHUNCO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Tanguiéta', 'TANGUIETE'], 'TANGUIETA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Toucountouna'], 'TOUCOUNTOUNA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Bassila'], 'BASSILA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Copargo'], 'COPARGO')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Djougou'], 'DJOUGOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Ouaké'], 'OUAKE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Bembèrèkè'], 'BEMBEREKE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Bonou'], 'BONOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Boukoumbé'], 'BOUKOUMBE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Cobly'], 'COBLY')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Kérou'], 'KEROU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Kouandé'], 'KOUANDE')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['SO0AVA'], 'SO-AVA')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Matéri'], 'MATERI')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['Natitingou'], 'NATITINGOU')
df_agroclimat['Communes'] = df_agroclimat['Communes'].replace(['AFANGNI'], 'IFANGNI')
    
st.dataframe(df_agroclimat.head(20))
df_agroclimat.fillna(0, inplace=True)
df_agroclimat[['Sup(ha)', 'Prod(T)']] = df_agroclimat[['Sup(ha)', 'Prod(T)']].apply(pd.to_numeric, errors='coerce')

st.write("Dimensions du dataframe :")
st.write(df_agroclimat.shape)

if st.checkbox("Afficher les valeurs manquantes") : 
    st.dataframe(df_agroclimat.isna().sum())
        
if st.checkbox("Afficher les doublons") : 
    st.write(df_agroclimat.duplicated().sum())
if st.checkbox("Afficher les types de données") : 
    st.write(df_agroclimat.dtypes)

# Print the unique departments and communes
st.write("Unique Departments:")
len(df_agroclimat['Departement'].unique()) # Use len() to get the count of elements in a NumPy array
st.write(len(df_agroclimat['Departement'].unique()))
st.write(df_agroclimat['Departement'].unique())

st.write("Unique Communes:")
st.write(len(df_agroclimat['Communes'].unique())) # Use len() to get the count of elements in a NumPy array
st.write(df_agroclimat['Communes'].unique())

st.write("\nUnique Produits:")
st.write(len(df_agroclimat['Produit'].unique())) # Use len() to get the count of elements in a NumPy array
st.write(df_agroclimat['Produit'].unique())

st.title("Statistiques descriptives")
st.write("Les statistiques descriptives nous permettent de comprendre la distribution des données et les tendances générales des différentes variables.")
stat_num = df_agroclimat.describe().drop('Annees', axis=1)
stat_obj = df_agroclimat.describe(include='object')
st.write("Statistiques descriptives des variables numériques :")
st.write(stat_num)
st.write("Statistiques descriptives des variables catégorielles :")
st.write(stat_obj)

st.title("## Les données agricoles sont structurées en 4 colonnes :")
st.write("1. Departement : Le département dans lequel la culture a été réalisée.")
st.write("2. Communes : La commune dans laquelle la culture a été réalisée.")
st.write("3. Produit : Le produit agricole cultivé.")
st.write("4. Annees : L'année de la culture.")

st.title("### Les données climatiques sont contitutées de plusieurs variables :")
st.write("1. Vitesse du vent : La vitesse du vent en km/h.")
st.write("2. La directio du vent : La direction du vent en degré.")
st.write("3. Pression atmosphérique : La pression atmosphérique en hPa.")
st.write("4. La température minimale : La température minimale en degré Celsius.")
st.write("5. La température maximale : La température maximale en degré Celsius.")
st.write("6. L'humidité relative : L'humidité relative en %.")
st.write("7. L'humidité spécifique : L'humidité spécifique en g/kg.")
st.write("8. Précipitation : La précipitation en mm.")
st.write("9. L'humidité du sous sol et en surface : L'humidité du sol en surface et en profondeur")

st.title("## Les données géographiques sont structurées en 3 colonnes :")
st.write("1. Departement : Le département dans lequel la commune est située.")
st.write("2. Communes : La commune.")
st.write("3. Latitude : La latitude de la commune.")
st.write("4. Longitude : La longitude de la commune.")

st.title("## Les produits agricoles sont classés en 4 catégories :")
st.write("1. Céréales : Maïs, Riz, Sorgho, Millet, etc.")
st.write("2. Légumineuses : Soja, Arachide, Haricot, etc.")
st.write("3. Tubercules : Manioc, Igname, Patate douce, etc.")
st.write("4. Autres : Ananas, Banane, Coton, etc.")
st.write("Les produits disponible pour cette analyse sont :")
st.write(df_agroclimat['Produit'].unique())


