"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQhhXp2ZTGyU_TqrVzCv7YxX-U9T__Pu

# EDA - Prétraitement et Compréhension des Données

**`Importation des librairies`**
"""
import pandas as pd
import numpy as np
import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
import geopandas as gpd

from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from statsmodels.tsa.arima.model import ARIMA
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
from sklearn.impute import SimpleImputer
from sklearn.model_selection import cross_val_score


df_agroclimat = pd.read_excel("agroclimat.xlsx")
geo = gpd.read_file("benin_geographie")


pages = {
    "AgroClimat": [
        st.Page("contexte.py", title="AgroClimat"),
        st.Page("explore.py", title="Exploration des données"),
    ],
    "Analyse Exploration des Données": [
        st.Page("eda_climat.py", title="Données climatiques"),
        st.Page("eda.py", title="Données agricoles"),
    ],
    "Relation entre Données Climatiques et Agricoles": [
        st.Page("impact.py", title="Influence et/ou Impact"),
        st.Page("matrix_corr.py", title="Matrix de Corrélation"),
    ],
    "Modélisation et Prévision": [
        st.Page("kmean.py", title="Modélisation"),
        st.Page("model.py", title="Prévision"),
    ],

    
}

pg = st.navigation(pages)

pg.run()